DEFAULT_FIELD_SIZE = 4
DEFAULT_WIN_CONDITION = 3  # сколько раз нужно найти предмет

# Ограничения
MIN_FIELD_SIZE = 3
MAX_FIELD_SIZE = 6
MIN_ITEMS_PER_FIELD = 2
MAX_ITEMS_PER_FIELD = 6
MAX_PLAYERS = 5