import os
from typing import Tuple, List

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ANSWERS_DIR = os.path.join(BASE_DIR, "resources")

BASE_MODES: List[str] = list([
    "normal_mode",
    "playful_mode",
    "cynical_mode",
    "flirty_mode",
    "mystic_mode",
    "tired_mode",
    "vamp_mode",
    "childish_mode",
    "chaos_mode"
])

RAGE_MODE_STATES: Tuple[str, str, str] = (
    "rage_mode/fury_mode",
    "rage_mode/growl_mode",
    "rage_mode/snarl_mode"
)

ALL_MODES: List[str] = BASE_MODES + ["rage_mode"]

MODE_LABELS = {
    "normal_mode": "🧘 Спокойствие",
    "playful_mode": "🎉 Игривость",
    "cynical_mode": "😒 Цинизм",
    "flirty_mode": "💋 Флирт",
    "mystic_mode": "🔮 Мистика",
    "tired_mode": "😴 Усталость",
    "vamp_mode": "🦇 Вампиризм",
    "childish_mode": "🧸 Детскость",
    "chaos_mode": "🌪️ Хаос",
    "rage_mode": "🔥 Ярость"
}

FILE_LABELS = {
    "cynical_mode/bitter_truth.txt": "🧂 Горькая правда",
    "cynical_mode/brutal_honesty.txt": "🪓 Безжалостная честность",
    "cynical_mode/dark_humour.txt": "🖤 Тёмный юмор",
    "cynical_mode/existential_dread.txt": "🕳️ Экзистенциальный ужас",
    "cynical_mode/nihilistic_answers.txt": "☠️ Нигилистические ответы",
    "cynical_mode/pessimistic_prediction.txt": "🌧️ Пессимистический прогноз",
    "cynical_mode/realistic_cynicism.txt": "📉 Реалистичный цинизм",
    "cynical_mode/sarcastic_wisdom.txt": "😏 Саркастическая мудрость",
    "cynical_mode/self_deprecating.txt": "🙃 Самоуничижение",
    "cynical_mode/social_commentary.txt": "📺 Социальный комментарий",
    "flirty_mode/cheeky_compliments.txt": "😉 Дерзкие комплименты",
    "flirty_mode/double_entendres.txt": "🍑 Двойные смыслы",
    "flirty_mode/flirty_challenges.txt": "🎯 Флирт-задания",
    "flirty_mode/naughty_questions.txt": "😈 Шаловливые вопросы",
    "flirty_mode/playful_teasing.txt": "👅 Игривые подначки",
    "flirty_mode/romantic_predictions.txt": "💘 Романтические предсказания",
    "flirty_mode/seductive_denial.txt": "🫦 Соблазнительные отказы",
    "flirty_mode/subtle_hints.txt": "🕊️ Тонкие намёки",
    "flirty_mode/suggestive_answers.txt": "🌹 Намекающие ответы",
    "flirty_mode/wink_wink_responses.txt": "😉 Подмигивающие фразы",
    "chaos_mode/absurd_analogies.txt": "🌀 Абсурдные аналогии",
    "chaos_mode/ai_overload.txt": "🤖 Перегрузка ИИ",
    "chaos_mode/biohazard_bugs.txt": "☣️ Биологические баги",
    "chaos_mode/kernel_panic.txt": "💥 Kernel Panic",
    "chaos_mode/meta_comments.txt": "🗨️ Мета-комментарии",
    "chaos_mode/network_anomalies.txt": "📡 Сетевые аномалии",
    "chaos_mode/pure_chaos.txt": "🧨 Чистый хаос",
    "chaos_mode/system_failures.txt": "💻 Системные сбои",
    "chaos_mode/time_paradoxes.txt": "⏳ Парадоксы времени",
    "chaos_mode/virtual_vandalism.txt": "🎮 Виртуальное хулиганство",
    "childish_mode/animal_answers.txt": "🐾 Животные ответы",
    "childish_mode/bedtime_answers.txt": "🌙 Ответы перед сном",
    "childish_mode/colorful_answers.txt": "🎨 Цветастые ответы",
    "childish_mode/fairy_tale_answers.txt": "🧚 Сказочные ответы",
    "childish_mode/food_answers.txt": "🍭 Еда как предсказание",
    "childish_mode/giggle_answers.txt": "😄 Хихикающие ответы",
    "childish_mode/magic_answers.txt": "✨ Волшебные ответы",
    "childish_mode/playful_answers.txt": "🤹 Игривые ответы",
    "childish_mode/rainbow_answers.txt": "🌈 Радужные ответы",
    "childish_mode/silly_answers.txt": "🤪 Глупые ответы",
    "mystic_mode/ancient_riddles.txt": "📜 Древние загадки",
    "mystic_mode/arcane_prophecies.txt": "🔮 Тайные пророчества",
    "mystic_mode/cryptic_warnings.txt": "☠️ Загадочные предостережения",
    "mystic_mode/crystal_visions.txt": "💎 Кристальные видения",
    "mystic_mode/moon_whispers.txt": "🌙 Шепот луны",
    "mystic_mode/phantom_echoes.txt": "👻 Призрачные эхо",
    "mystic_mode/runes_revelations.txt": "ᚱ Рунические откровения",
    "mystic_mode/shadow_truths.txt": "🌑 Тени истины",
    "mystic_mode/spirit_guidance.txt": "🕯️ Руководство духов",
    "mystic_mode/tarot_wisdom.txt": "🃏 Мудрость Таро",
    "normal_mode/balanced_responses.txt": "⚖️ Сбалансированные ответы",
    "normal_mode/basic_wisdom.txt": "📘 Простая мудрость",
    "normal_mode/casual_replies.txt": "💬 Неформальные ответы",
    "normal_mode/direct_answers.txt": "➡️ Прямые ответы",
    "normal_mode/neutral_guidance.txt": "🧭 Нейтральное руководство",
    "normal_mode/simple_truths.txt": "🔎 Простые истины",
    "normal_mode/straightforward.txt": "📏 Без лишнего",
    "normal_mode/typical_predictions.txt": "📅 Типичные предсказания",
    "normal_mode/uncomplicated.txt": "🔧 Неприхотливые ответы",
    "normal_mode/wolf_instincts.txt": "🐺 Инстинкты волка",
    "playful_mode/absurd_imagery.txt": "🎭 Абсурдные образы",
    "playful_mode/animal_antics.txt": "🐒 Зверские выходки",
    "playful_mode/funny_metaphors.txt": "😂 Забавные метафоры",
    "playful_mode/mischievous_replies.txt": "😼 Шаловливые ответы",
    "playful_mode/playful_teasing.txt": "🎯 Игривые подколки",
    "playful_mode/roleplay_responses.txt": "🎲 Ролевые ответы",
    "playful_mode/silly_jokes.txt": "🃏 Дурашливые шутки",
    "playful_mode/tongue_twisters.txt": "👅 Скороговорки",
    "playful_mode/whimsical_answers.txt": "🪄 Причудливые ответы",
    "playful_mode/wolf_puns.txt": "🐺 Волчьи каламбуры",
    "rage_mode/fury_mode/final_warning.txt": "🚨 Последнее предупреждение",
    "rage_mode/fury_mode/insulting.txt": "💢 Оскорбления",
    "rage_mode/fury_mode/last_chance.txt": "⏳ Последний шанс",
    "rage_mode/fury_mode/pack_mentality.txt": "🐺 Стая на подходе",
    "rage_mode/fury_mode/property_damage.txt": "🧱 Разрушения имущества",
    "rage_mode/fury_mode/threatening.txt": "🗡️ Угрозы",
    "rage_mode/fury_mode/unfiltered.txt": "🤬 Без цензуры",
    "rage_mode/fury_mode/violent_imagery.txt": "🔥 Жестокие образы",
    "rage_mode/fury_mode/warning_responses.txt": "⚠️ Предупреждающие ответы",
    "rage_mode/growl_mode/final_warning.txt": "🚨 Последнее предупреждение",
    "rage_mode/growl_mode/insulting.txt": "💢 Оскорбления",
    "rage_mode/growl_mode/last_chance.txt": "⏳ Последний шанс",
    "rage_mode/growl_mode/pack_mentality.txt": "🐺 Стая на подходе",
    "rage_mode/growl_mode/property_damage.txt": "🧱 Разрушения имущества",
    "rage_mode/growl_mode/threatening.txt": "🗡️ Угрозы",
    "rage_mode/growl_mode/unfiltered.txt": "🤬 Без цензуры",
    "rage_mode/growl_mode/violent_imagery.txt": "🔥 Жестокие образы",
    "rage_mode/growl_mode/warning_responses.txt": "⚠️ Предупреждающие ответы",
    "rage_mode/snarl_mode/final_warning.txt": "🚨 Последнее предупреждение",
    "rage_mode/snarl_mode/insulting.txt": "💢 Оскорбления",
    "rage_mode/snarl_mode/last_chance.txt": "⏳ Последний шанс",
    "rage_mode/snarl_mode/pack_mentality.txt": "🐺 Стая на подходе",
    "rage_mode/snarl_mode/property_damage.txt": "🧱 Разрушения имущества",
    "rage_mode/snarl_mode/threatening.txt": "🗡️ Угрозы",
    "rage_mode/snarl_mode/unfiltered.txt": "🤬 Без цензуры",
    "rage_mode/snarl_mode/violent_imagery.txt": "🔥 Жестокие образы",
    "rage_mode/snarl_mode/warning_responses.txt": "⚠️ Предупреждающие ответы",
    "tired_mode/barely_awake.txt": "😴 Едва проснулся",
    "tired_mode/energy_saver.txt": "🔋 Режим энергосбережения",
    "tired_mode/exhausted_thoughts.txt": "💤 Измождённые мысли",
    "tired_mode/half_asleep.txt": "🌘 Полусонные фразы",
    "tired_mode/lazy_answers.txt": "🛋️ Ленивые ответы",
    "tired_mode/low_effort.txt": "🪫 Минимум усилий",
    "tired_mode/napping_soon.txt": "😪 Скоро дрема",
    "tired_mode/need_coffee.txt": "☕ Нужно кофе",
    "tired_mode/sleepy_responses.txt": "🛌 Сонные отклики",
    "tired_mode/yawn_inducing.txt": "🥱 Навевающее зевоту",
    "vamp_mode/bat_puns.txt": "🦇 Каламбуры с летучими мышами",
    "vamp_mode/bloody_humor.txt": "🩸 Кровавый юмор",
    "vamp_mode/coffin_answers.txt": "⚰️ Ответы из гроба",
    "vamp_mode/dark_charms.txt": "🕸️ Тёмные чары",
    "vamp_mode/eternal_mysteries.txt": "♾️ Вечные тайны",
    "vamp_mode/fangs_revealing.txt": "🧛 Обнажение клыков",
    "vamp_mode/gothic_prophecies.txt": "🕯️ Готические пророчества",
    "vamp_mode/nocturnal_whispers.txt": "🌙 Ночные шепоты",
    "vamp_mode/seductive_night.txt": "💋 Соблазн ночи",
    "vamp_mode/transylvanian_wisdom.txt": "🏰 Трансильванская мудрость",
}